### ISSUE TITLE
Can't initiate two repository with different paths in the same python session

### ISSUE THREAD

**Issue by hhsecond** [tensorwerk/hangar-py#4]
I found an issue with initiating the repository again and again in the same python session even if the repository path is different. Because of the singleton nature of `Environment` class, regardless of the path, we pass for a repository, all the following repositories will have the path of the first repository (Is this something we desire to have?)

The below script can reproduce the issue. The last print statement must print `True`
```python
import numpy as np
from hangar.repository import Repository

test_hangar_path1 = '/home/hhsecond/mypro/test_hangar_dir_1'
arr1 = np.random.random((5, 7))
repo1 = Repository(path=test_hangar_path1)
repo1.init(user_name='tester1', user_email='foo@test1.bar', remove_old=True)
co = repo1.checkout(write=True)
dset1 = co.datasets.init_dataset('dset1', prototype=arr1)
dset1['arr1'] = arr1
co.commit()
co.close()


test_hangar_path2 = '/home/hhsecond/mypro/test_hangar_dir_2'
arr2 = np.random.random((5, 7))
repo2 = Repository(path=test_hangar_path2)
repo2.init(user_name='tester2', user_email='foo@test2.bar', remove_old=True)
co = repo2.checkout(write=True)
dset2 = co.datasets.init_dataset('dset2', prototype=arr2)
dset2['arr2'] = arr2
co.commit()
co.close()


print(test_hangar_path2, repo2._repo_path)
print(test_hangar_path2 == repo2._repo_path)
```

**Comment by rlizzo** [comment]
So I think for right now it would be best to not allow this usage pattern. It's something I would like to fix, but I don't think it's particularly high on the priority list right now. 

To really solve this problem we should get rid of the Singleton's scattered around the codebase. They could probably be removed in the hdf5FileHandler and TransactionRegister with only mild headaches if we were to tie their lifespan to the Repository instance. The real issue is for the Environments class which sets up lmdb envs. Lmdb dbs absolutely need to only be opened once per process, or really bad things happened (the behavior is rather well documented, but i learned just how bad it gets the hard way...) Singleton's were my solution to that particular headache, but if you have another idea I'd love to hear it!

In lieu of a redesign at the Environment level, I think we should just raise an error if a second repo instance is created in a particular process. That would be pretty easy to implement.

Thoughts?

**Comment by rlizzo** [comment]
So i may have to eat my words here a bit with #20. It actually seems to be a decent solution to this issue... though we still . will want to kill the singletons hanging around the codebase sometime in the future.
